<?php

return [
    'agency' => [
        'slug' => 'ttc',
        'name' => 'Toronto Transit Commission',
    ],
    'lines' => [
        [
            'id' => '1',
            'name' => 'Line 1 Yonge-University',
            'aliases' => ['line 1', 'yonge-university', 'yonge university'],
        ],
        [
            'id' => '2',
            'name' => 'Line 2 Bloor-Danforth',
            'aliases' => ['line 2', 'bloor-danforth', 'bloor danforth'],
        ],
        [
            'id' => '3',
            'name' => 'Line 3 Scarborough',
            'aliases' => ['line 3', 'scarborough rt'],
        ],
        [
            'id' => '4',
            'name' => 'Line 4 Sheppard',
            'aliases' => ['line 4', 'sheppard line'],
        ],
    ],
    'stations' => [
        ['slug' => 'union', 'name' => 'Union', 'aliases' => ['union station'], 'lines' => ['1']],
        ['slug' => 'st-george', 'name' => 'St George', 'aliases' => ['st. george'], 'lines' => ['1', '2']],
        ['slug' => 'bloor-yonge', 'name' => 'Bloor-Yonge', 'aliases' => ['bloor yonge'], 'lines' => ['1', '2']],
        ['slug' => 'spadina', 'name' => 'Spadina', 'aliases' => [], 'lines' => ['1', '2']],
        ['slug' => 'eglinton', 'name' => 'Eglinton', 'aliases' => [], 'lines' => ['1']],
        ['slug' => 'st-clair', 'name' => 'St Clair', 'aliases' => ['st. clair'], 'lines' => ['1']],
        ['slug' => 'finch', 'name' => 'Finch', 'aliases' => [], 'lines' => ['1']],
        ['slug' => 'kipling', 'name' => 'Kipling', 'aliases' => [], 'lines' => ['2']],
        ['slug' => 'kennedy', 'name' => 'Kennedy', 'aliases' => [], 'lines' => ['2', '3']],
        ['slug' => 'sheppard-yonge', 'name' => 'Sheppard-Yonge', 'aliases' => ['sheppard yonge'], 'lines' => ['1', '4']],
        ['slug' => 'don-mills', 'name' => 'Don Mills', 'aliases' => [], 'lines' => ['4']],
    ],
    'routes' => [
        ['id' => '1', 'name' => 'Line 1 Subway'],
        ['id' => '2', 'name' => 'Line 2 Subway'],
        ['id' => '3', 'name' => 'Line 3 Subway'],
        ['id' => '4', 'name' => 'Line 4 Subway'],
        ['id' => '501', 'name' => 'Queen'],
        ['id' => '503', 'name' => 'Kingston Rd'],
        ['id' => '504', 'name' => 'King'],
        ['id' => '505', 'name' => 'Dundas'],
        ['id' => '506', 'name' => 'Carlton'],
        ['id' => '509', 'name' => 'Harbourfront'],
        ['id' => '510', 'name' => 'Spadina'],
        ['id' => '511', 'name' => 'Bathurst'],
        ['id' => '512', 'name' => 'St Clair'],
        ['id' => '300', 'name' => 'Bloor-Danforth Night Bus'],
        ['id' => '301', 'name' => 'Queen Night Bus'],
        ['id' => '304', 'name' => 'King Night Bus'],
        ['id' => '306', 'name' => 'Carlton Night Bus'],
        ['id' => '310', 'name' => 'Spadina Night Bus'],
        ['id' => '320', 'name' => 'Yonge Night Bus'],
        ['id' => '329', 'name' => 'Dufferin Night Bus'],
        ['id' => '352', 'name' => 'Lawrence West Night Bus'],
        ['id' => '365', 'name' => 'Parliament Night Bus'],
        ['id' => '395', 'name' => 'York Mills Night Bus'],
        ['id' => '29', 'name' => 'Dufferin'],
        ['id' => '35', 'name' => 'Jane'],
        ['id' => '39', 'name' => 'Finch East'],
        ['id' => '52', 'name' => 'Lawrence West'],
        ['id' => '60', 'name' => 'Steeles West'],
        ['id' => '900', 'name' => 'Airport Express'],
    ],
];
